save_loc: /scratch/koustuvs/clutrr_2.0/
rule_store: rule_bases/clutrr
world_prefix: world # was rule in v1.0
seed: 40
world_id: 0
world_mode: # can be train/valid/test or None
num_graphs: 20000 # max number of graphs (set a bit higher to allow all graphs to generate)
num_train_graphs: 1000
num_valid_graphs: 100
num_test_graphs: 100
search_multiplier: 4 # number of times num_graphs will be multiplied to expand the search
re_index: True
test_size: 0.2
max_path_len: 5 # Number of relations : max_path_len - 1
add_noise: False
num_steps: 50
expansion_prob: 0.5
num_completion_steps: 10
randomize_node_id: False
world_graph:
  sample: False
  num_sampled_paths: 100
  num_steps: 100
  expansion_prob: 0.5
  num_completion_steps: 100
  max_path_len: 10
# Clutrr specific args - optional, can provide blank
train_descriptor_lengths: 2,3,4
val_descriptor_lengths: 3,4
test_descriptor_lengths: 3,4
